#!/bin/ksh
# /etc/rc.d/chn init file for launching seckc_mhn_api as a service on OpenBSD 

daemon="/opt/chnserver/seckc-mhn-dashboard-api/venv/bin/uwsgi"
daemon_flags="--ini /opt/chnserver/seckc-mhn-dashboard-api/uwsgi.ini  --daemonize /opt/chnserver/seckc-mhn-dashboard-api/logs/uwsgi.log"
daemon_user="chn"
daemon_timeout=30

. /etc/rc.d/rc.subr

pexp=".*uwsgi.*seckc_mhn_dashboard_api.*"
rc_bg=YES
rc_reload=NO

rc_cmd $1
